services:
    netbull_core.form.type.dynamic:
        class: NetBull\CoreBundle\Form\Type\DynamicType
        tags:
            - { name: form.type }
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '%netbull_core.form_types.ajax.page_limit%'

    netbull_core.form.type.ajax:
        class: NetBull\CoreBundle\Form\Type\AjaxType
        tags:
            - { name: form.type }
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '%netbull_core.form_types.ajax.minimum_input_length%'
            - '%netbull_core.form_types.ajax.page_limit%'

    netbull_core.form.type.select2:
        class: NetBull\CoreBundle\Form\Type\Select2Type
        tags:
            - { name: form.type }
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '%netbull_core.form_types.ajax.minimum_input_length%'
            - '%netbull_core.form_types.ajax.page_limit%'
            - '%netbull_core.form_types.ajax.allow_clear%'
            - '%netbull_core.form_types.ajax.delay%'
            - '%netbull_core.form_types.ajax.language%'
            - '%netbull_core.form_types.ajax.cache%'

    netbull_core.form.type.phone_number:
        class: NetBull\CoreBundle\Form\Type\PhoneNumberType
        tags:
            - { name: form.type, alias: tel }

    netbull_core.service.translation:
        class: NetBull\CoreBundle\Form\Type\TranslationForm
        arguments: ['@form.registry', '@doctrine']

    netbull_core.listener.translations:
        class: NetBull\CoreBundle\Form\EventListener\TranslationsListener
        arguments: ['@netbull_core.service.translation']

    netbull_core.type.translations:
        class: NetBull\CoreBundle\Form\Type\TranslationsType
        tags:
            - { name: form.type, alias: netbull_translations }
        arguments: ['@netbull_core.listener.translations', '%allowed_locales%', '%locale%']

    netbull_core.type.translationsfields:
        class: NetBull\CoreBundle\Form\Type\TranslationsFieldsType
        tags:
            - { name: form.type, alias: netbull_translationsFields }
