services:
    netbull_core.service.translation:
        class: NetBull\CoreBundle\Form\TranslationForm
        arguments: ['@form.registry', '@doctrine']

    netbull_core.subscriber.translations:
        class: NetBull\CoreBundle\Form\EventListener\TranslationsSubscriber
        arguments: ['@netbull_core.service.translation', '@form.factory']

    netbull_core.type.translations:
        class: NetBull\CoreBundle\Form\Type\TranslationsType
        tags:
            - { name: form.type, alias: netbull_translations }
        arguments: ['@netbull_core.subscriber.translations', '%netbull_core.locale.allowed_locales%', '%locale%']

    netbull_core.type.translationsfields:
        class: NetBull\CoreBundle\Form\Type\TranslationsFieldsType
        tags:
            - { name: form.type, alias: netbull_translationsFields }
